theme: jekyll-theme-minimal
title: Julius Alphonso
description: Resume for Julius Alphonso
logo: https://res.cloudinary.com/drigushc2/image/upload/c_scale,r_13,w_300/v1540622228/samples/animals/three-dogs.jpg
show_downloads: false
