theme: jekyll-theme-minimal
title: Julius Alphonso
description: [juliusalphonso@pm.me](mailto:juliusalphonso@pme.me) | [GitHub](https://github.com/JadeMaveric) | [LinkedIn ](https://www.linkedin.com/in/JuliusAlphonso/)| [Kaggle](https://www.kaggle.com/juliusalphonso) | [Twitter](https://twitter.com/JuliusAlphonso)
logo: https://res.cloudinary.com/drigushc2/image/upload/c_crop,e_auto_color,g_face:center,h_885,w_707,x_1284,y_0/a_0/v1599329138/20200307_121821_HDR.jpg
show_downloads: false
